name: Cucumber Reporting CI

on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build_package_and_report:
    name: Validate Cucumber Reporting

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        node-version: [16.x, 18.x, 20.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build Package
        run: |
          npm ci
          npm run compile
          npm pack
          node scripts/move-package-to-demo.js

      - name: Generate Report
        working-directory: ./demo
        run: |
          npm i
          npm run build:report:esm
          npm run build:report:cjs
