name: github-pages

on:
  push:
    branches:
      - master # upload demo report only from main branch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run compile

      - name: Build Package and Move to Test Directroy
        run: |
          npm pack
          mv som30ind-cucumber-reporting-*.tgz ./test/lib/cucumber-reporting.tgz

      - name: Generate Report
        working-directory: ./test
        run: |
          npm i
          npm run build:report

      - uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          external_repository: som30ind/som30ind.github.io
          personal_token: ${{ secrets.GH_PAGES_UPLOAD }}
          publish_branch: master
          publish_dir: ./test/report
